import = [
"/usr/lib/node_modules/alacritty-themes/themes/Ayu-Dark.toml"
]
live_config_reload = true

[font]
size = 12
builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "bold_italic"

[shell]
program = "/usr/bin/zsh"
args = [ "-l" ]

[window]
opacity = 0.85
blur = true

[window.padding]
x = 5
y = 5

[scrolling]
history = 10_000
multiplier = 10

[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = true

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.footer_bar]
foreground = "#ffffff"
background = "#0087d7"

[colors.selection]
text = "#ffffff"
background = "#0087d7"

[colors.line_indicator]
foreground = "#ffffff"
background = "#800000"

[colors.search.matches]
foreground = "#181818"
background = "#ac4242"

[colors.search.focused_match]
foreground = "#181818"
background = "#f4bf75"

[colors.hints.start]
foreground = "#181818"
background = "#f4bf75"

[colors.hints.end]
foreground = "#181818"
background = "#ac4242"

[colors.normal]
black = "#181818"
red = "#ac4242"
green = "#00af00"
yellow = "#f4bf75"
blue = "#6a9fb5"
magenta = "#aa759f"
cyan = "#75b5aa"
white = "#d8d8d8"

[colors.bright]
black = "#6b6b6b"
red = "#c55555"
green = "#aac474"
yellow = "#feca88"
blue = "#82b8c8"
magenta = "#c28cb8"
cyan = "#93d3c3"
white = "#f8f8f8"

[colors.dim]
black = "#0f0f0f"
red = "#712b2b"
green = "#5f6f3a"
yellow = "#a17e4d"
blue = "#456877"
magenta = "#704d68"
cyan = "#4d7770"
white = "#8e8e8e"

[bell]
animation = "Linear"
duration = 0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
unfocused_hollow = true
thickness = 0.15

[cursor.style]
shape = "Beam"
blinking = "Off"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Right"
mods = "Control"
action = "Paste"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true

[hints.enabled.binding]
key = "?"
mods = "Control|Shift"

[keyboard]
bindings = [
{ key = "N",            mods = "Control|Shift", action = "CreateNewWindow"  },
{ key = "V",            mods = "Control|Shift", action = "Paste"            },
{ key = "C",            mods = "Control|Shift", action = "Copy"             },
{ key = "Key0",         mods = "Control",       action = "ResetFontSize"    },
{ key = "0",            mods = "Control",       action = "ResetFontSize"    },
{ key = "=",            mods = "Control",       action = "IncreaseFontSize" },
{ key = "NumpadAdd",    mods = "Control",       action = "IncreaseFontSize" },
{ key = "Minus",        mods = "Control",       action = "DecreaseFontSize" },
{ key = "-",            mods = "Control",       action = "DecreaseFontSize" },
{ key = "Return",       mods = "Control|Shift", action = "SpawnNewInstance" },
{ key = "F",            mods = "Control",       action = "ToggleFullScreen" },
{ key = ".",            mods = "Control",       action = "ClearSelection"   },
{ key = "t",            mods = "Control|Shift",       action = "ToggleViMode"     },
]
