import = [ "/usr/lib/node_modules/alacritty-themes/themes/Zenburn.toml" ]
live_config_reload = true

[font]
size = 17
builtin_box_drawing = true

  [font.normal]
  family = "Inconsolata Nerd Font Mono"
  style = "regular"

  [font.bold]
  family = "Inconsolata Nerd Font Mono"
  style = "bold"

  [font.italic]
  family = "Inconsolata Nerd Font Mono"
  style = "italic"

  [font.bold_italic]
  family = "Inconsolata Nerd Font Mono"
  style = "bold_italic"

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.85
blur = true
decorations = "Buttonless"

  [window.dimensions]
  columns = 150
  lines = 100

  [window.padding]
  x = 8
  y = 2

[scrolling]
history = 10_000
multiplier = 10

[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = true

  [colors.cursor]
  text = "CellBackground"
  cursor = "CellForeground"

  [colors.footer_bar]
  foreground = "#ffffff"
  background = "#0087d7"

  [colors.selection]
  text = "#ffffff"
  background = "#0087d7"

  [colors.line_indicator]
  foreground = "#ffffff"
  background = "#800000"

[colors.search.matches]
foreground = "#181818"
background = "#ac4242"

[colors.search.focused_match]
foreground = "#181818"
background = "#f4bf75"

[colors.hints.start]
foreground = "#181818"
background = "#f4bf75"

[colors.hints.end]
foreground = "#181818"
background = "#ac4242"

[bell]
animation = "Linear"
duration = 0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
unfocused_hollow = true
thickness = 0.15

  [cursor.vi_mode_style]
  shape = "Block"

  [cursor.style]
  shape = "Beam"
  blinking = "Always"

[mouse]
hide_when_typing = true

  [[mouse.bindings]]
  mouse = "Right"
  mods = "Control"
  action = "Paste"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false

  [hints.enabled.mouse]
  enabled = true

  [hints.enabled.binding]
  key = "?"
  mods = "Control|Shift"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "="
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "NumpadAdd"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "-"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "F"
mods = "Control"
action = "ToggleFullScreen"

[[keyboard.bindings]]
key = "."
mods = "Control"
action = "ClearSelection"

[[keyboard.bindings]]
key = "t"
mods = "Control|Shift"
action = "ToggleViMode"
