#!/bin/bash

# Using xset to set times for DPMS

xset s on
xset s 1800 1800
xset +dpms dpms 1800 1800 1800 

# Faster key repeat and delay
xset r rate 210 40

xrandr --dpi 144

# export XMODIFIERS=@im=ibus
# export GTK_IM_MODULE="ibus"
# export QT_IM_MODULE="ibus`"
# ibus-daemon

# keychain ~/.ssh/id_rsa
# [ -f ~/.keychain/$HOSTNAME-sh ] && . ~/.keychain/$HOSTNAME-sh 2>/dev/nullglob
# source /usr/share/doc/find-the-command/ftc.zsh info quiet
