#!/bin/sh
while read -r file
do
    case "$1" in
        "w") feh --bg-scale "$file" & ;;
        # "c")
        #     [ -z "$destdir" ] && destdir="$(sed "s/#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs | awk '{print $2}' | rofi -dmenu -l 5 -i -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
        #     [ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
        #     cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." &
        #     ;;
        # "m")
        #     [ -z "$destdir" ] && destdir="$(sed "s/#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs | awk '{print $2}' | dmenu -l 20 -i -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
        #     [ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
        #     mv "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file moved to $destdir." &
        #    ;;
        "e") 
            dest=$(fd --type d -d 1 | rofi -dmenu -l 10 -p "Destination")
            cp "$file" "$dest"
            notify-send "Files copied: '$file' to '$dest'" ;;
        "r") convert -rotate 90 "$file" "$file" ;;
        "R") convert -rotate -90 "$file" "$file" ;;
        "f") convert -flop "$file" "$file" ;;
        "y") printf "%s" "$file" | tr -d '\n' | xclip -selection clipboard &&
             notify-send "$file copied to clipboard" & ;;
        "Y") readlink -f "$file" | tr -d '\n' | xclip -selection clipboard &&
             notify-send "$(readlink -f "$file") copied to clipboard" & ;;
        "d") [ "$(printf "No\\nYes" | rofi -dmenu -i -l 1 -p "Really delete $file?")" = "Yes" ] && 
             rm "$file" && notify-send "$file deleted." ;;
        # "g") if installed gimp && setsid -f gimp "$file" ;;
        "i") mediainfo "$(readlink -f $file)" | yad --text-info --width=820 --height=450 --button=Close:1 & ;;
        "t") alacritty -e echo $file ;;
    esac
done
